### ISSUE TITLE
Backend: Creating Hubs with friendly names and visiblity

### ISSUE THREAD

**Issue by latikak** [latikak/covey.town#2]
This issue will track the creation of HubStore and HubController and will involve the operations and modifications in each hub.

**Comment by tahseen31** [comment]
**Engineering:**

// Hub Controller class implements logic for each Hub on the backend.

HubController:

// Create Hubs with HubName, visibility for the RoomId provided
Constructor(hubname, visibility, roomid)

Getters and Setters: 
1.	Players
2.	Occupancy
3.	Hubname
4.	Hub_id
5.	Room_id

Methods:
1.	List_of_players (list of players inside a Hub)
2.	AddPlayersToHub (When player enters, prompt for password and let them in/deny access)
3.	DestroyPlayers (When room or hub is destroyed, destroy all player sessions for hub)
4.	UpdatePlayer(Avatar/location) (Update a player’s Location/Avatar when inside a hub)

// Hub Store 

Track all the Hubs for a given Room

Methods:

1. getHubControllerForRoom(find Hub controller for a given room ID)
2. listHubsForRoom (list of Hubs in a room)
3. updateHub(update name, password or visibility of a Hub)
4. DeleteHub (when Room is deleted, destroy Hub for the given RoomId)

**Comment by tahseen31** [comment]
**Documentation:**

1. Write Documentation on creating a Hub
2. Write Documentation on getting list of players inside a Hub
3. Write Documentation on adding players to hub
4. Write Documentation on updating players in a hub
5. Write Documentation on destroying players in a hub
6. 4. Write Documentation on checking occupancy of a hub
7.  Write Documentation on updating a hub
8. 4. Write Documentation on deleting a hub

**Infrastructure:**
We will pull the latest version of Covey.Town after successful implementation of HW-4 so that we have the up to date version of Covey.Town to extend backend of covey.Town Service.

Unit Tests:

// Hub Controller

1.	Creates Hub with name and visibility for the roomID
2.	Get Players for Hub
3.	Add new Players to Hub
4.	Update a player inside Hub
5.	When Hub is deleted, all players must be destroyed

// Hub Store

1.     Get Instance of Hub in a given Room
2.	List Public Hubs
3.	Does not list Private Hubs
4.	Get Occupancy of Hub  
5.	When Room is Deleted, its corresponding hubs must also be deleted
