### ISSUE TITLE
User(Avatar) isolation in Hubs

### ISSUE THREAD

**Issue by latikak** [latikak/covey.town#6]

**Comment by Archanajith** [comment]
Engineering : 
Resemble something like ParticipantInfo.tsx inside a building .
Possible addition to backend to consider number of users in the building .

Documentation : 
https://www.twilio.com/docs/video/migrating-1x-2x#object-model

Infrastructure :  
Check Assignment 4 and see if any of that is getting added to this.

**Comment by Archanajith** [comment]
Engineering :
- Resemble  ParticipantInfo.tsx inside a building .
- In the inside of a Hub ( consider it as a Hub Class ) , it's state must consist of nearByPlayers 
   nearByPlayers : Players [ ]
- The nearByPlayers renders all the players inside the building .
- To maintain the state , HubAppState must be defined in CoveyTypes.ts . This will keep a track of the state of a particular Hub.
  export type HubAppState = {
  userName: string,
  hubFriendlyName: string,
  hubID:string,
  myPlayerID: string,
  players: Player[],
  currentLocation: UserLocation,
  nearbyPlayers: NearbyPlayers,
  emitMovement: (location: UserLocation) => void,
  socket: Socket | null,
  apiClient: HubServiceClient,
 };
- Create a method getAllPlayersHub(String hubFriendlyName , String hubId) to get the list of players inside a hub in HubServiceClient .

Documentation :
https://www.twilio.com/docs/video/migrating-1x-2x#object-model

Infrastructure :
We will pull the latest version of Covey.Town after successful implementation of HW-4 so that we have the up to date version of Covey.Town to build our frontend on top of it.

Since this is a frontend feature , there is no way of testing if each player has a different icon other than manually testing it .
